ChatTestWeb/Models/ErrorViewModel.cs
namespace ChatTestWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ChatTestWeb/Controllers/ChatController.cs
using Data.Models;
using Infra.Helper;
using Microsoft.AspNetCore.Mvc;

namespace ChatTestWeb.Controllers
{
    public class ChatController : Controller
    {
        public IActionResult ChatView()
        {
            return View();
        }

        public IActionResult _chatlist()
        {
            return PartialView("_chatlist");
        }

        public async Task<IActionResult> _userlist(int id)
        {
            var users = await UserRequestHelper.GetAllUserExcept(id);
            return PartialView("_userlist", users);

        }

        public async Task<IActionResult> IdentifyUser(string username)
        {
            var user = await UserRequestHelper.GetUserByUsername(username);
            if (user == null)
            {
                return NotFound();
            }
            return Ok(user);
        }

        public async Task<IActionResult> GetSpecificChatData(int fromuserid, int touserid)
        {
            var chatdata = await ChatRequestHelper.GetSpecificChatData(fromuserid, touserid);
            return Ok(chatdata);
        }

        public async Task<IActionResult> InsertChatData(string message, int fromuserid, int touserid)
        {
            var chatdata = await ChatRequestHelper.InsertChatData(message, fromuserid, touserid);
            return Ok(chatdata);
        }

        public async Task<IActionResult> InsertChat(tbChat chat)
        {
            chat.accesstime = DateTime.UtcNow;
            var data = await ChatRequestHelper.InsertChat(chat);
            return Ok(data);
        }
    }
}

ChatTestWeb/Controllers/HomeController.cs
using ChatTestWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ChatTestWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ChatTestWeb/Controllers/PostController.cs
using Data.Models;
using Infra.Helper;
using Microsoft.AspNetCore.Mvc;

namespace ChatTestWeb.Controllers
{
    public class PostController : Controller
    {
        [HttpGet]
        public IActionResult PostView()
        {
            return View();
        }
        public IActionResult _postlist()
        {
            return PartialView("_postlist");
        }
        public IActionResult _addpost(int userId)
        {
            tbPost post = new tbPost();
            post.userId = userId;
            return PartialView("_addpost", post);

        }
        public IActionResult _addpostbase64(int userId)
        {
            tbPost post = new tbPost();
            post.userId = userId;
            return PartialView("_addpostbase64", post);

        }
        public async Task<IActionResult> GetAllPosts()
        {

            var postdata = await PostRequestHelper.GetAllPosts();
            
            if (postdata == null)
            {
                return NotFound();
            }

            return PartialView("_postlist", postdata);
        }
        [HttpPost]
        public async Task<IActionResult> InsertPost(tbPost post, IFormFile files)
        {
            post.accessTime = DateTime.Now;
            if (files != null)
            {
                string fileName = Path.GetFileName(files.FileName);
                post.postPhoto = fileName;
                string uploadpath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\ImageUpload", fileName);
                var stream = new FileStream(uploadpath, FileMode.Create);
                files.CopyToAsync(stream);
            }
            var postdata = await PostRequestHelper.UpSert(post);
            return Ok(postdata);
        }

        public static string GetFileExtension(string base64String)
        {
            var data = base64String.Substring(0, 5);

            switch (data.ToUpper())
            {
                case "IVBOR":
                    return "png";
                case "/9J/4":
                    return "jpg";
                case "AAAAF":
                    return "mp4";
                case "JVBER":
                    return "pdf";
                case "AAABA":
                    return "ico";
                case "UMFYI":
                    return "rar";
                case "E1XYD":
                    return "rtf";
                case "U1PKC":
                    return "txt";
                case "MQOWM":
                case "77U/M":
                    return "srt";
                default:
                    return string.Empty;
            }
        }
        public async Task<IActionResult> InsertPostBase64(tbPost post)
        {
            post.accessTime = DateTime.Now;
            if (post.postPhoto != null)
            {
                var ext = GetFileExtension(post.postPhoto);

                string imageName = Guid.NewGuid() + "." + ext;

                //set the image path
                string imgPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\ImageUpload", imageName);

                byte[] imageBytes = Convert.FromBase64String(post.postPhoto);

                System.IO.File.WriteAllBytes(imgPath, imageBytes);

                post.postPhoto = imageName;
            }

            var postdata = await PostRequestHelper.UpSert(post);

            return Ok(postdata);
        }
        public async Task<IActionResult> GetCommentByPost(int postId)
        {
            var commentdata = await CommentRequestHelper.GetCommentByPost(postId);
            if (commentdata == null)
            {
                return NotFound();
            }
            return PartialView("_commentview", commentdata);
        }
        [HttpPost]
        public async Task<IActionResult> AddComment(tbComment comment)
        {
            comment.AccessTime = DateTime.Now;
            var commentdata = await CommentRequestHelper.AddComment(comment);
            return Ok(commentdata);
        }

    }
}

ChatTestWeb/Views/Chat/ChatView.cshtml
<div id="userlist">
</div>

<div class="mt-3">
	<div id="chatlist"></div>
</div>



@section scripts{
	<script>
		"use strict";

		var connection = new signalR.HubConnectionBuilder().withUrl("https://localhost:7200/chathub").build();

		connection.start().then(function () {
			console.log("Signal R Connection started")
		}).catch(function (err) {
			console.log(err)
		})

		let sendToUserId = null;
		let currentUserId = parseInt(localStorage.getItem("userid"));
		var robotImageUrl = 'https://s3-us-west-2.amazonaws.com/chrisnielsen/robot.png';
		let lastuserid;
		let nextuserid;
		
		function UserIdentifier(){
			const getUsername = localStorage.getItem("username");
			const getUserId = localStorage.getItem("userid");
			if(getUsername == null || getUserId == null){
				let username = prompt("Please State Your Identifier");
				$.ajax({
					cache: false,
					url: '@Url.Action("IdentifyUser", "Chat")',
					data: {username},
					beforeSend: function(){

					},
					success: function(response){
						if(response != null){
							localStorage.setItem("username", username);
							localStorage.setItem("userid", response.id);
							CallUserListPartial();
						}
					},
					error: function(error){
						console.log(error);
					}
				})
			}else{
				CallUserListPartial();
				//return;
			}
		}

		$(function(){
			//local storage settting
			UserIdentifier();
			//user list button UI with ajax
			

			connection.on("SendMessage", function (message, fromUserId, toUserId) {
				nextuserid = sendToUserId;
				var currentappid = currentUserId;
				if (fromUserId === currentUserId) {
					addToLog(message, true, nextuserid, currentappid, "row");
				}
				else if (currentUserId === toUserId) {
					$('#log div.message:last').find("img").remove()
					addToLog(message, false, nextuserid, currentappid, "row");
				}
			})
		})

		function CallUserListPartial(){
			const id = localStorage.getItem("userid");
			$.ajax({
				cache: false,
				url: '@Url.Action("_userlist", "Chat")',
				data: {id},
				type: "GET",
				success: function(response){
					$("#userlist").empty().append(response);
					$("button").click(function() {
						let touserid = parseInt(this.id);
						sendToUserId = parseInt(this.id);
						const fromuserid = localStorage.getItem("userid");
						CallChatListPartial(fromuserid, sendToUserId);
					});
				},
				error: function(error){
					console.log(error)
				}
			})
		}

		function CallChatListPartial(fromuserid, touserid) {
			
			$.ajax({
				cache: false,
				url: '@Url.Action("_chatlist", "Chat")',
				beforeSend: function () {

				},
				success: function (response) {
					$("#chatlist").empty().append(response);
					$.ajax({
						cache: false,
						url: '@Url.Action("GetSpecificChatData", "Chat")',
						data: {fromuserid, touserid},
						type: "GET",
						beforeSend: function(){

						},
						success: function(result){
							let getUserid = parseInt(localStorage.getItem("userid"));
							
							// Cartoon vector designed by Freepik
							// http://www.freepik.com/free-photos-vectors/cartoon
							// Pre-load image
							$('<img/>')[0].src = robotImageUrl;
							//response.forEach((data) => {
							//	var nextuserid = data.fromUserId;
							//	if (data.fromUserId === getUserid) {

							//		addToLog(data.message, true, nextuserid);
							//	}else{
							//		addToLog(data.message, false, nextuserid);
							//	}
							//	lastuserid = data.fromUserId;
							//})

							console.log(result);

							for(var j = 0; j < result.length; j++){
								
								for(var i = 0; i < result[j].chat.length ; i++){
								   var response = result[j].chat;
								   nextuserid = (response[i - 1] != null ? response[i - 1].fromUserId : "");
								   var currentappid = response[i].fromUserId; 
								   if (response[i].fromUserId === getUserid) {
									
										addToLog(response[i].message, true, nextuserid, currentappid, response[i].accesstime);
									}else{
										addToLog(response[i].message, false, nextuserid, currentappid, response[i].accesstime);
									}
								}

								var $log = $('.log');

								var $date = $(`<div class="clearfix"></div><div class="row"><div class="col-md-12"><div class="date" style="display: flex;justify-content: center;">${moment(result[j].key).format('MMMM Do YYYY, h:mm:ss a')}</div></div></div>`);

								$log.prepend($date);
								
							}

							$("#fromUserId").val(currentUserId);
							$("#toUserId").val(sendToUserId);
							
							$('#messageForm').submit(function (event) {
								
								event.preventDefault();
								//var fromuserid = currentUserId;
								//var touserid = sendToUserId;
								//var $userInput = $(this).find('#message');
								var userinput = document.getElementById("message");
								
								$.ajax({
									cache: false,
									url: '@Url.Action("InsertChat", "Chat")',
									type: "POST",
									data: $(this).serialize(),
									beforeSend: function () {
									},
									success: function (data) {
										var message = userinput.value;
										//connection.invoke('SendMessage', message, currentUserId, sendToUserId).catch(function (error) {
										//	console.log(error);
										//})
										//$userInput.val('');
										userinput.value = ""
									},
									complete: function () {
										
									},
									error: function (error) {
										console.log(error);
									}
								})
							});
							

							
						},
						complete: function(){
							
						},
						error: function(error){
							console.log(error)
						}
					})
					
				},
				error: function (error) {
					console.log(error);
				}
			})
		}

		function addToLog(message, user, nextuserid, currentappid, opt, accesstime) {
			var $message = $('<div class="message animated" style="display: flex;"></div>');
			var $chattime = $('<div class="chattime"></div>');
			var currentDate = new Date();
			var convertedDate = new Date(accesstime);
			if(convertedDate >= currentDate){
				$chattime.html();
			}
			
			if (!user) {
				if (currentappid != nextuserid) {

					var $picture = $('<div class="robotImg"><img src="' + robotImageUrl + '"></img><div>');
					$message.append($picture);
				}
				
			}

			var $content = $('<div class="content"></div>');
			$content.html(message);
			$message.append($content);

			var $log = $('.log');
			if(opt == "row"){
				$log.append($message);

			}else{
				$log.prepend($message);

			}
			
			if (user) {
				$message.addClass('user');
			}

			$log.animate({ scrollTop: $log[0].scrollHeight }, "slow", 'linear');

			setTimeout(function () {
				if (user) {
					$message.addClass('user');
					$message.addClass('fadeInRightBig');
				} else {
					$message.addClass('fadeInLeftBig');
				}
			}, 0);
		}
	</script>
}

ChatTestWeb/Views/Chat/_chatlist.cshtml
@model Data.Models.tbChat

<style>
    * {
        font-family: 'Raleway', sans-serif;
    }

    html, body {
        height: 100%;
    }

    .chat-log {
        position: relative;
        align-content: center;
        align-items: center;
        width: 100%;
        max-width: 600px;
        height: 90%;
        border: 1px solid #f7f7f7;
    }

    .log {
        height: calc(100% - 50px);
        overflow-y: auto;
    }

    .input {
        background-color: #F7F7F7;
        height: 50px;
    }

    .user-input {
        color: #B4B7BF;
        background-color: transparent;
        width: calc(100% - 90px);
        border: 0px;
        font-size: 1.1em;
        line-height: 50px;
        margin-left: 20px;
        outline: none;
    }

    button {
        color: #B4B7BF;
        background-color: transparent;
        border: 0px;
        width: 60px;
        padding: 14px;
        outline: none;
        display: inline-block;
        cursor: pointer;
    }

    .message {
        margin: 20px;
        font-size: 1em;
        opacity: 1;
        float: left;
        clear: both;
    }

        .message.user {
            float: right;
            clear: both;
        }

        .message img {
            width: 50px;
            float: left;
        }

    .content {
        background: #8DABE3;
        color: #ffffff;
        padding: 15px;
        border-radius: 5px;
        float: left;
        margin-left: 15px;
    }

    .user .content {
        color: #868995;
        background: #f7f7f7;
        max-width: none;
    }


    .credit {
        margin-top: 20px;
    }
</style>

<div class="chat-log">
    <div class="log" id="log">
    </div>
    <div class="input">
        <form id="messageForm">
            <input type="hidden" name="fromUserId" asp-for="fromUserId" id="fromUserId" />
            <input type="hidden" name="toUserId" asp-for="toUserId" id="toUserId" />
            <input type="text" class="user-input" placeholder="message..." asp-for="message" name="message" id="message" />
            <button>
                <i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i>
            </button>
        </form>
    </div>
</div>

ChatTestWeb/Views/Chat/_userlist.cshtml
@model IEnumerable<Data.Models.tbUser>

<style>
	.users{
		position: relative;
		display: flex;
	}
</style>

<div class="users">
	@foreach(var user in Model){
		<div>
			<button type="button" class="btn btn-info" style="margin-left: 10px;" id="@user.id">@user.username</button>
		</div>
	}
</div>

ChatTestWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4 fw-bold">Welcome To Bulky Book Store.</h1>
</div>

ChatTestWeb/Views/Post/PostView.cshtml
<h2>Posts</h2>

<button type="button" class="btn btn-primary mb-5" data-bs-toggle="modal" data-bs-target="#addPostModal" onclick="load_addform()">
    + Upload Post (Multipart/Form-Data Image)
</button>
<button type="button" class="btn btn-primary mb-5" data-bs-toggle="modal" data-bs-target="#addPostModalBase64" onclick="load_addform2()">
    + Upload Post (Base64 Image With Compression)
</button>

<div id="loading mt-5">
    <div class="spinner-border" role="status"></div>
<span class="sr-only h3 ms-3"> Posts Loading. Please Wait....</span>
   </div>
<div id="postlist">
</div>

<div class="modal fade" id="addPostModal" tabindex="-1" aria-labelledby="addPostModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="formholder"></div>
        </div>

    </div>
</div>

<div class="modal fade" id="addPostModalBase64" tabindex="-1" aria-labelledby="addPostModalLabelBase64" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="formholderBase64"></div>
        </div>

    </div>
</div>

@section scripts{
    <script>
        "use strict";
        
        function UserIdentifier(){
            const getUsername = localStorage.getItem("username");
            const getUserId = localStorage.getItem("userid");
            if (getUsername == null || getUserId == null){
                let username = prompt("Please Enter Username");
                $.ajax({
                    cache: false,
                    url: '@Url.Action("IdentifyUser", "Chat")',
                    data: {username},
                    success: function(response){
                        if(response != null){
                            localStorage.setItem("username", username);
                            localStorage.setItem("userid", response.id);
                            getPost();
                      
                        }
                 
                    },
                    error: function(error){
                        console.log(error)
                    }
                })
            }else{
                getPost();
            }
        }

        $(function(){
            UserIdentifier();
           
           
        })

        function getPost(){
            $.ajax({
                cache: false,
                url: "../Post/getallposts",
                type: "GET",
                success: function(response){
                    $("#postlist").empty().append(response);
                    $("#loading").empty();
                  
                },
                error: function(error){
                    console.log(error)
                }
            })
        }

        function load_addform(){
            const userId = localStorage.getItem("userid");
            form(userId)
        }
        function load_addform2(){
            const userId = localStorage.getItem("userid");
            popup_modalform(userId, '#addPostModalBase64', '#formholderBase64', "../Post/_addpostbase64", form_submit_base64)
        }

        function form(userId) {
            popup_modalform(userId, '#addPostModal',
                '#formholder', "../Post/_addpost", form_submit);
        }
        

        function popup_modalform(userId, modal, formholder, url, callback) {
            $.ajax({
                cache: false,
                url: url,
                data: { userId : userId },
                beforeSend: function () {
                    showmodal(modal)
                },
                success: function (result) {
                    $(formholder).empty().append(result);
                    callback();

                },
                complete: function () { }
            });
        }

        

        function form_submit() {
            $('#addForm').submit(function (e) {
                e.preventDefault();
                var formData = new FormData();
                const userId = localStorage.getItem("userid");
                $("#addForm").find("input[type=file]").each(function(index,field){
                    const file = field.files;
                    for(var i = 0; i < file.length; i++){
                        formData.append("files", file[i]);
                    }
                })


                var otherModal = {
                    "Id":0,
                    "userId": userId,
                    "postContent": $("#post_content").val(),
                    "isDeleted" : false
                }

                for (var key in otherModal) {
                    formData.append(key, otherModal[key]);
                }
                $.ajax({
                    cache: false,
                    url: "../Post/InsertPost",
                    type: "Post",
                    contentType: false,
                    processData: false,
                    data: formData,
                    dataType: 'json',
                    beforeSend: function () {
                        $('.btn').prop("disabled", true);
                    },
                    success: function (myData) {
                      getPost();
                    },
                    complete: function () {
                        hidemodal("#addPostModal");
                        $('.btn').prop("disabled", false);
                    }
                });

            });
        }
        function FileOnChange(){
            //var reader = new FileReader();
            //reader.readAsDataURL(file);
            //reader.onload = function () {
            //    console.log(reader.result);//outputs random looking characters for the image
            //    // Return the result in the callback
            //    //cb(reader.result.split(",")[1]);
            //    $("#postPhoto").val(reader.result);
            //};
            //reader.onerror = function (error) {
            //    console.log('Error: ', error);
            //};

            $('#upload').change(function () {
                var input = this;
                var url = $(this).val();
                var ext = url.substring(url.lastIndexOf('.') + 1).toLowerCase();

                //const MAX_WIDTH = 800; // Set maximum width of resized image
                //const MAX_HEIGHT = 800; // Set maximum height of resized image
                const QUALITY = 0.5;

                const canvas = document.getElementById('canvas');
                const ctx = canvas.getContext('2d');
                const imageInput = document.getElementById('upload');

                    const file = this.files[0];
                    var reader = new FileReader();

                    reader.onload = function (e) {
                    const img = new Image();
                    img.addEventListener('load', function () {
                        let width = img.width;
                        let height = img.height;

                        // Check if image needs to be resized
                        //if (width > MAX_WIDTH) {
                        //    height *= MAX_WIDTH / width;
                        //    width = MAX_WIDTH;
                        //}
                        //if (height > MAX_HEIGHT) {
                        //    width *= MAX_HEIGHT / height;
                        //    height = MAX_HEIGHT;
                        //}

                        canvas.width = width;
                        canvas.height = height;

                        // Draw image on canvas with resized dimensions
                        ctx.drawImage(img, 0, 0, width, height);

                        
                        // Get resized image data as a base64 encoded JPEG
                        //const resizedImage = canvas.toDataURL('image/jpeg');
                        //console.log(resizedImage);
                        canvas.toBlob(function (blob) {
                            console.log(file.name, " ", file.type);
                            const compressedFile = new File([blob], file.name, { type: file.type });
                            console.log("Blob : ", blob);
                            const finalcompressed = canvas.toDataURL('image/jpeg', 50/100);
                            console.log(finalcompressed);
                            $("#postPhoto").val(finalcompressed.split(",")[1]);
                        }, file.type, QUALITY);
                       
                        //$("#postPhoto").val(resizedImage.split(",")[1]);
                    });
                   img.src = this.result;
               //     $("#postPhoto").val(e.target.result.split(",")[1]);
                 
                    }
                    reader.readAsDataURL(file);

            });
        }



        function form_submit_base64() {
            FileOnChange();
            $('#addFormBase64').submit(function (e) {
                e.preventDefault();
       
                const userId = localStorage.getItem("userid");
    
                $.ajax({
                    cache: false,
                    url: "../Post/InsertPostBase64",
                    type: "Post",
                    data: $(this).serialize(),
                    beforeSend: function () {
                        $('.btn').prop("disabled", true);
                    },
                    success: function (myData) {
                        getPost();
                    },
                    complete: function () {
                        hidemodal("#addPostModalBase64");
                        $('.btn').prop("disabled", false);
                    }
                });

            });
        }

        function showmodal(div) {
            $(div).modal('show');
        }

        function hidemodal(div) {
            $(div).modal('hide');
        }
        //comment section

        function load_comment(postId) {
            $.ajax({
                cache: false,
                url: "../Post/GetCommentByPost",
                data: { postId: postId },
                type: "GET",
                beforeSend: function () {

                },
                success: function(response) {
                    $('#div_post_' + postId).toggle();

                    $('#div_post_' + postId).empty().append(response);
                },
                 complete: function () {

                }
            });
        }

        function add_comment(postId){
            const commenterId = localStorage.getItem("userid");
            var obj = {
                "Id":0,
                "PostId" : postId,
                "CommenterId" : commenterId,
                "Comment": $('#comment_form_' + postId).val(),
                "IsDeleted" : false
            };
            $.ajax({
                cache: false,
                url: "../Post/AddComment",
                type: "Post",
                data: {comment: obj},
                beforeSend: function(){

                },
                success: function(){
                  load_comment(postId);
                }
            });
        }
        // Post Photos

        

    </script>
}

ChatTestWeb/Views/Post/_addpost.cshtml
@model Data.Models.tbPost

<!-- Modal -->

<div class="modal-header">
    <h5 class="modal-title" id="addPostModalLabel">Add New Post (using multipart)</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
 @using (Html.BeginForm("InsertPost", "Post", FormMethod.Post, new { @id="addForm", @enctype= "multipart/form-data"}))
    {
    <input type="hidden" name="ID" value="@Model.Id" />
    <input type="hidden" name="userId" value="@Model.userId" />
    <div class="modal-body">
        <div class="input-group mb-3">
            <input type="text" class="form-control" id="post_content" placeholder="Insert ur post..." name="PostContent" value="@Model.postContent" aria-label="PostContent" aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-3">
            <input type="file" class="form-control" name="PostPhoto" value="@Model.postPhoto" aria-label="PostPhoto" aria-describedby="basic-addon1">
        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
    </div>
    }
   

ChatTestWeb/Views/Post/_addpostbase64.cshtml
@model Data.Models.tbPost

<!-- Modal -->

<div class="modal-header">
    <h5 class="modal-title" id="addPostModalLabelBase64">Add New Post (using base 64)</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<form id="addFormBase64">
    <input type="hidden" name="ID" value="@Model.Id" />
    <input type="hidden" name="userId" value="@Model.userId" />
    <input type="hidden" name="postPhoto" value="@Model.postPhoto" id="postPhoto" />
    <div class="modal-body">
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Insert ur post..." name="PostContent" value="@Model.postContent" aria-label="PostContent" aria-describedby="basic-addon1">
        </div>
        <p>! Inserted Image will be compressed to 50% of its size ! </p>
        <div class="input-group mb-3">
            <input type="file" class="form-control" id="upload" value="@Model.postPhoto" aria-label="PostPhoto" aria-describedby="basic-addon1"><br />
        </div>
        <canvas id="canvas" class="align-items-center justify-content-center" style="max-width: 400px;"></canvas>

    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
    </div>
</form>

ChatTestWeb/Views/Post/_commentview.cshtml
@model Data.ViewModel.CommentMainModel

<p class="fw-bold h5 my-1">Comments : @Model.model.Count()</p>
    @if(Model.model.Count() > 0){
        <ul class="list-group" id="comments">
            @foreach(var data in Model.model)
            {
                <li class="list-group-item" id="@data.comment.Id">
                    <p class="float-left">@data.comment.Comment</p>
                    <p class="float-end">Commented By: @data.user.username -
                    @data.comment.AccessTime
                    </p>

                </li>
            }
            
    </ul>
}
else
{
    <h5>No Comments Here Yet.</h5>
}
<form>
    <div class="form-group mt-2">
        <input type="text" class="form-control" id="comment_form_@Model.PostId" aria-describedby="commentHelp" placeholder="Enter comment">
      
    </div>
    <button type="button" class="btn btn-primary mt-1" onclick="add_comment(@Model.PostId)">Add Comment</button>
</form>